IS_TEST: True

MODEL:
  TYPE: DeepLab

DATASET:
  ROOT: "./tests/dataset/dummy_dataset"
  LIST_TRAIN: "config/dataset/lists/dummy_train.txt"
  LIST_VAL: "config/dataset/lists/dummy_val.txt"
  LIST_TEST: "config/dataset/lists/dummy_test.txt"
  INPUT:
    SENSOR: s2
    USED_CHANNELS: [3,2,1,12]
    STATS_FILE: "config/dataset/stats/test.json"
    CHANNELS: ["B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B8a", "B9", "B10", "B11", "B12"]
  MASK:
    SENSOR: lc
    CONFIG: "config/dataset/mask_configs/test.yml"
  CLASSES_COUNT_JSON: "config/dataset/stats/classes_count_test.json"
TRAIN:
  EPOCHS: 2
  RESUME_CHECKPOINT: ""
  BATCH_SIZE_PER_DEVICE: 2
  DEVICE: "cpu"
  WORKERS: 0
  SHUFFLE: True
  SEED: 42
  LOSS:
    TYPE: "categorical_crossentropy"
    USE_WEIGHTS: True
  OPTIMIZER: "adam"
  LR: 0.001
  WEIGHT_DECAY: 0.0005
  VERBOSE_STEP: 1
  VAL_PER_EPOCH: 1
  WEIGHTS_FOLDER: "tests/weights"
  USE_COMET: False
  COMET_TAGS: ["test"]
  DATA_AUG:
    RANDOM_RESIZE_CROP:
      USE: True
      SCALE: [0.9, 1.1]
      RATIO: [0.9, 1.1]
      PROBABILITY: 0.6
    HORIZONTAL_FLIP:
      USE: True
      PROBABILITY: 0.5
    VERTICAL_FLIP:
      USE: True
      PROBABILITY: 0.5
TEST:
  DEVICE: "cpu"
  WORKERS: 0
  BATCH_SIZE_PER_DEVICE: 1