maskname2int:
  IGBP: 0
  LCCS_LC: 1
  LCCS_LU: 2
  LCCS_SH: 3
channels_priority: ["LCCS_LU", "LCCS_SH"]
selected_masks:
  LCCS_LU:
    0: [9]
    1: [25, 35, 36]
  LCCS_SH:
    2: [1]
    3: [2]
    4: [3]
    5: [10]
    6: [20]
    7: [27, 50]
    8: [30]
    9: [40]
    10: [51]
    0: [0]
class2label:
  0: "urban"
  1: "agricultural"
  2: "barren"
  3: "snow"
  4: "water"
  5: "dense_forest"
  6: "open_forest"
  7: "wetlands"
  8: "grasslands"
  9: "shrublands"
  10: "tundra"
class_importance:
  0: 2
  1: 2
  2: 1
  3: 1
  4: 2
  5: 1
  6: 0.8
  7: 0.5
  8: 1
  9: 0.5
  10: 0.2

# Visualization
alpha: 0.3
colors:
  1: [200, 200, 200]
  2: [195, 255, 84]
  3: [255,211,92]
  4: [255, 255, 255]
  5: [60, 38, 201]
  6: [2, 110, 40]
  7: [6, 143, 54]
  8: [100, 143, 16]
  9: [151, 166, 22]
  10: [186, 201, 157]
  11: [9, 69, 15]
MASKS_METADATA_PATH:  "/data/seg_data/masks_metadata_default.csv"