maskname2int:
  IGBP: 0
  LCCS_LC: 1
  LCCS_LU: 2
  LCCS_SH: 3
channels_priority: ["LCCS_LU", "LCCS_SH"]
selected_masks:
  LCCS_LU:
    1: [9]
    2: [25]
    3: [35]
    4: [36]
  LCCS_SH:
    5: [1]
    6: [3]
    7: [10, 20]
    8: [27, 50]
    9: [30]
    10: [40]
    11: [51]
    0: [0, 2]
class2label:
  1: "urban"
  2: "forest_cropland_mosaics"
  3: "herbaceous_cropland_mosaics"
  4: "herbaceous_cropland"
  5: "barren"
  6: "water"
  7: "forest"
  8: "wetlands"
  9: "grasslands"
  10: "shrublands"
  11: "tundra"
  0: "other"

# Visualization
alpha: 0.3
colors:
  1: [200, 200, 200]
  2: [195, 255, 84]
  3: [255,211,92]
  4: [255, 255, 255]
  5: [60, 38, 201]
  6: [2, 110, 40]
  7: [6, 143, 54]
  8: [100, 143, 16]
  9: [151, 166, 22]
  10: [186, 201, 157]
  11: [9, 69, 15]
  0: [0, 0, 0]
MASKS_METADATA_PATH:  "/data/seg_data/masks_metadata_v2.csv"