maskname2int:
  IGBP: 0
  LCCS_LC: 1
  LCCS_LU: 2
  LCCS_SH: 3
channels_priority: ["LCCS_LU", "LCCS_SH"]
selected_masks:
  LCCS_LU:
    1: [9]
    2: [25, 35, 36]
  LCCS_SH:
    3: [1]
    4: [2]
    5: [3]
    6: [10]
    7: [20]
    8: [27, 50]
    9: [30]
    0: [51, 40]
    1: [0]
class2label:
  0: "shrublands"
  1: "urban"
  2: "agricultural"
  3: "barren"
  4: "snow"
  5: "water"
  6: "dense_forest"
  7: "open_forest"
  8: "wetlands"
  9: "grasslands"
class_importance:
  0: 1
  1: 2
  2: 2
  3: 2
  4: 1
  5: 2
  6: 1
  7: 1
  8: 1
  9: 1

# Visualization
alpha: 0.3
colors:
  0: [186, 201, 157]
  1: [200, 200, 200]
  2: [195, 255, 84]
  3: [255,211,92]
  4: [255, 255, 255]
  5: [60, 38, 201]
  6: [2, 110, 40]
  7: [6, 143, 54]
  8: [100, 143, 16]
  9: [151, 166, 22]
MASKS_METADATA_PATH:  "/data/seg_data/masks_metadata_less_classes.csv"