maskname2int:
  mask_1: 0
  mask_2: 1
channels_priority: ["mask_1", "mask_2"]
selected_masks:
  mask_1:
    1: [1]
    2: [2, 3, 4]
  mask_2:
    3: [1]
    4: [2, 4]
    0: [0]
class2label:
  1: "class_1"
  2: "class_2"
  3: "class_3"
  4: "class_4"
  0: "other"
class_importance:
  1: 1
  2: 1
  3: 1
  4: 1
  0: 1
# Visualization
alpha: 0.6
colors:
  1: [200, 200, 200]
  2: [195, 255, 84]
  3: [255,211,92]
  4: [255, 255, 255]
  0: [0, 0, 0]
MASKS_METADATA_PATH:  "config/dataset/mask_configs/masks_metadata_test.csv"