maskname2int: 
  mask_1: 0
  mask_2: 1
channels_priority: ["mask_1", "mask_2"]
selected_masks:
  mask_1:
    1: [1]
    2: [2, 3, 4]
  mask_2:
    3: [1]
    4: [2, 4]
    0: [0]
class2label:
  1: "class_1"
  2: "class_2"
  3: "class_3"
  4: "class_4"
  0: "other"