# It will be visible in Actions tab in your repo
name: Integration Test

# Specify when the action should be run
on:
  pull_request:
  push:
    branch: [master, training_loop]

jobs:
  build:
    # Specify the OS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Specify here the python version 
        # (it should match environment created in the CI pipeline)
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # Creating environment
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install pipenv
        python -m pipenv install --dev --deploy --system
    # Running tests
    - name: Test with pytest
      run: |
        python -m pipenv run pytest tests/